### ISSUE TITLE
Image size too small for 5 scale IW-SSIM evaluation

### ISSUE THREAD

**Issue by sendjasni** [obartra/ssim#137]
Hello,

I'm trying to compute IW-SSIM  of two images with size of `2048x4096`, but I'm getting this message instead, and the iw-ssim value = `-inf`

```matlab
Image size too small for 5 scale IW-SSIM evaluation
```

**Comment by obartra** [comment]
Hi @sendjasni, thanks for the interest

The Matlab implementation is only used to inform the JS implementation, I downloaded it directly from [here](https://ece.uwaterloo.ca/~z70wang/research/iwssim/) but I'm afraid I know very little about it.

I was able to get it to run to compare results of both implementations but I'm not familiar with the details.

**Comment by sendjasni** [comment]
Hi @obartra, thanks to you for your prompt response. I did some digging and I found that the input images to the iwssim function must be single-channel images, it's just that the message shown  does not indicates the exact issue.
Thanks again.

I think i'll close this issue.
