### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by lonelyclick** [obartra/ssim#160]
Now I have a scenario to test the stability of mobile devices. The performance requirements are relatively high. It needs to complete 224 wide and high picture detection within 20 ms. can we improve the performance through wasm?

Here are my test results：[macbook pro 2018 chrome]
![image](https://user-images.githubusercontent.com/8056201/71554826-5f753d00-2a5f-11ea-8792-bf599bc4e882.png)

**Comment by obartra** [comment]
Oh hey there thanks for the interest! I don't have experience with wasm but I'm all for trying it if we can add node and browser support.

Before we go down that path though, have you tried the bezkrovny version (see [options](https://github.com/obartra/ssim/wiki/Usage#options))?

Another option that will dramatically improve performance is downsampling the image.

For the test images you are using I usually get the opposite results on a similar machine (reading the image taking ~100ms and ssim about ~30ms) any chance these values are flipped?

**Comment by lonelyclick** [comment]
I tried options, but the performance on the iPhone 8 plus is still not good. If bezkrovny is set, the accuracy is not enough, so it is necessary to improve the performance. Can we try wasm or webgl, and switch conveniently?

```
const { mssim, performance } = ssim(imageData, this.imageData, {
  ssim: 'fast',
  downsample: 'fast',
});

console.log(`SSIM: ${mssim} (${performance}ms)`);
```

- iPhone 8 Plus
- image width and height:  320px
- time: 50ms~

**Comment by obartra** [comment]
Got it, yeah bezkrovny won't give the same results although it correlates fairly well with perceived image degradation as well, I talked about it more [here](https://github.com/obartra/ssim/blob/master/generate/bezkrovny/README.md)

I've updated the [node/web example](https://ssim-comparison.glitch.me/) to give more info on the different performances and generated values.

But if you've tried all this and the results and / or performance are still not good enough, let's look into other options.

I had tried a previous implementation with typed arrays but didn't get the performance boost I expected (operations were faster but array creation was slower so it ended up being a wash) so I suspect webgl won't give us much gain but I could be wrong.

Would you be interested in taking a crack at a wasm or webgl implementation? I can help but I don't have enough bandwidth to own the full implementation at the moment

**Comment by obartra** [comment]
I've looked into adding wasm support but it'd take more time than I can dedicate to it right now.

I'll go ahead and close this issue since I'm not actively working on it but feel free to create a new one if you want to take a crack it
