### ISSUE TITLE
Add Contributor License Agreement

### ISSUE THREAD

**Issue by omnisip** [obartra/ssim#269]
We should add a contributor license agreement for the project that all contributors can sign off on before their work is accepted.  This ensures that project never runs into any licensing, ownership, or liability issues and Oscar can still lead and direct the project like he wants to.

For reference, these are the two most common CLAs I've found:

https://cla.developers.google.com/about/google-individual
https://code.facebook.com/cla/individual

They appear to be virtually identical.  

Ubuntu/Canonical's is slightly different, but offers the same legal protection:
https://ubuntu.com/legal/contributors/agreement

**Comment by obartra** [comment]
Done through https://cla-assistant.io/

**Comment by omnisip** [comment]
This says SAP in the CLA Assistant.  We need to fix that to be your name.
:-)

**Comment by obartra** [comment]
🤦 

updated
