### ISSUE TITLE
Question about the ImageData type

### ISSUE THREAD

**Issue by tjoskar** [obartra/ssim#282]
Hi,

I'm using this lib in a nodejs environment, which means I have no access to the [`ImageData`](https://developer.mozilla.org/en-US/docs/Web/API/ImageData)-class but that is fine since ssim don't use that one. But you are using the type so in order to use this lib with typescript I either need to add `"lib": ["DOM"]` in my tsconfig.json or copy the type from typescripts dom lib. 

Have to consider creating your own type for `ImageData` and remove the dependency to the DOM?

Thanks for the lib,

**Comment by obartra** [comment]
Oops sorry about that, I did not realize, yeah we can definitely create our own types for this, limiting it to the subset of properties we are actually using. More to your point we should probably also remove "DOM" from the tsconfig lib to ensure we don't rely on any other DOM-specific APIs.

Are you interested in making a contribution?

**Comment by tjoskar** [comment]
Thanks @obartra, I created a PR where I removed `DOM` from tsconfig.
