### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by 3400442579** [obartra/ssim#302]
![image](https://user-images.githubusercontent.com/34226979/122502117-96128f00-d028-11eb-9a8f-ea92216f0d7e.png)

console.info(gframes[i].pixels);
console.info(gframes[i + 1].pixels);
var ssim = window.ssim.default;
var out = ssim(gframes[i].pixels, gframes[i + 1].pixels ,{ ssim: "bezkrovny" });

<script src="https://unpkg.com/ssim.js@@latest/dist/ssim.web.js"></script>

**Comment by obartra** [comment]
Could it be that the image is too large? Have you tried downsampling?

**Comment by TalkLounge** [comment]
Workaround:

```js
const { ssim } = require("ssim.js");
const { createCanvas, loadImage } = require("canvas");

async function generateImageData(file) {
    const image = await loadImage(file);
    const canvas = createCanvas(image.width, image.height);
    const context = canvas.getContext('2d');
    context.drawImage(image, 0, 0);
    return {
        data: context.getImageData(0, 0, image.width, image.height).data,
        width: image.width,
        height: image.height
    };
}

async function init() {
    console.log(ssim(await generateImageData("C:/img1.jpg"), await generateImageData("C:/img2.jpg")));
}

init();
```
