### ISSUE TITLE
Argument of type 'Promise<unknown>' is not assignable to parameter of type 'ImageData'.

### ISSUE THREAD

**Issue by airda2895** [obartra/ssim#309]
Hi, I'm getting this error when trying to use `ssim` on Angular (TypeScript). I don't know if I'm doing something wrong, but it looks like the code which is supposed to load the image, returns a type of object which `ssim`doesn't expect.

My code:
```
@HostListener('document:keydown', ['$event']) onKeyDown = (e: any) => {
    if(e.key === 's') {
      const img1 = this.loadImage("./img1.jpg");
      const img2 = this.loadImage("./img2.jpg");

      const { mssim, performance } = ssim(img1, img2); // Error on this line

      console.log(`SSIM: ${mssim} (${performance}ms)`);
    }
  }

private getLimitDimensions(
    width: number,
    height: number,
    limit?: number
  ) {
    if (limit && width >= limit && height >= limit) {
      const ratio = width / height;
  
      if (ratio > 1) {
        return { height: limit, width: Math.round(limit / ratio) };
      }
      return { height: Math.round(limit * ratio), width: limit };
    }
    return { width, height };
  }
  
  private loadImage(url: string, limit = 0) {
    const img = new Image()

    return new Promise((resolve, reject) => {
      img.onload = () => {
        const { width, height } = this.getLimitDimensions(img.width, img.height, limit)
  
        if (width === 0 || height === 0) {
          return reject('Failed to load image')
        }
  
        this.gameContentEl.width = width
        this.gameContentEl.height = height
  
        this.gameContentCX.drawImage(img, 0, 0, img.width, img.height, 0, 0, width, height)
        return resolve(this.gameContentCX.getImageData(0, 0, width, height))
      }
      img.onerror = reject
      img.src = url
    })
  }
```
<img width="1104" alt="Screenshot 2022-02-23 at 15 44 42" src="https://user-images.githubusercontent.com/45570407/155342293-23d580a8-d57b-4890-9531-66a97e4bd7bf.png">

**Comment by obartra** [comment]
Bones Adrià!

This seems more of an issue with the types than the library, the library expect an object with ImageData properties. Here, if `getImageData` returns an object that matches that criteria (not sure if it does) you can cast it and do `resolve(this.gameContentCX.getImageData(0, 0, width, height) as ImageData)`

**Comment by airda2895** [comment]
> Bones Adrià!
> 
> This seems more of an issue with the types than the library, the library expect an object with ImageData properties. Here, if `getImageData` returns an object that matches that criteria (not sure if it does) you can cast it and do `resolve(this.gameContentCX.getImageData(0, 0, width, height) as ImageData)`

Thanks @obartra!

I've just tried that, but unfortunately, I keep getting the same error:
<img width="1398" alt="Screenshot 2022-02-23 at 17 31 59" src="https://user-images.githubusercontent.com/45570407/155363598-40844b61-9811-4c0d-9e53-873aae22ade2.png">
