### ISSUE TITLE
I am sorry but I do not know How to do it? The example is an old version?

### ISSUE THREAD

**Issue by catbao** [obartra/ssim#311]
import ssim from "ssim.js";

const img1 = loadImage("./img1.jpg");
const img2 = loadImage("./img2.jpg");

const { mssim, performance } = ssim(img1, img2);

console.log(`SSIM: ${mssim} (${performance}ms)`);

The version id not correct！ I want know how to do it.

**Comment by obartra** [comment]
Hi there, thanks for contributing!

Can you provide some more details? What error are you getting? What have you tried? It will help us debug this more easily

**Comment by catbao** [comment]
Thank you for your patience.
My problem maybe like:
If I run the code in the RunKit+npm like follows,  it wil be wrong like this. 
I think the problem is the version, but I do not know what's the correct version to make it work.
![Q9K2J`K8QQ5FLY929OUK%$3](https://user-images.githubusercontent.com/52957986/159112364-e1029c8f-3b31-4f92-a161-7ac850c56c77.png)
.

**Comment by obartra** [comment]
Apologies for the delayed response. I suspect animated gifs won't work but I also haven't tried runkit. I see now that the demo link on the README is broken, this is the link [to view the code](https://glitch.com/edit/#!/ssim-comparison) and [this one](https://ssim-comparison.glitch.me/) is for the rendered app.

Note that you need to import ssim as:

```js
const { ssim } = require("ssim.js");
```
