### ISSUE TITLE
bmp tests might be incorrect

### ISSUE THREAD

**Issue by jkeys089** [obartra/ssim#319]
In the test suite BMP images are being decoded using [bmp-js](https://github.com/shaozilee/bmp-js) which decodes into ABGR.
All other formats are being decoded by [node-canvas](https://github.com/Automattic/node-canvas) which decodes into RGBA.

As far as I can tell, there is no conversion from ABGR => RGBA happening for bmp's but tests are still passing.
If I force the use of canvas to decode bmp images then the tests start failing.

I believe this means the bmp tests are incorrect, right? Sorry if I'm missing something here.

Thanks!

**Comment by obartra** [comment]
Interesting, the results were saved as snapshots as they were and it just made sure the results were highly correlated with the original ssim paper values.

So there may very well be an issue there. Is this something you would want to contribute as a fix?

**Comment by jkeys089** [comment]
@obartra sure, I’ll send a PR.
