### ISSUE TITLE
Error generating SSIM [RangeError: Array size is not a small enough positive integer.]

### ISSUE THREAD

**Issue by aymeric75** [obartra/ssim#321]
Hello,

I executed your code in my React Native app:

        try {
          const out = ssim(image.uri, image.uri)
        } catch(err) {
          console.error('Error generating SSIM', err);
        }

Where :

`image.uri` is `file:///var/mobile/Containers/Data/Application/1717D736-86D8-464B-93F5-1A36DC7F79DE/Library/Caches/ExponentExperienceData/%2540anonymous%252FAwesomeProject-1ce63279-ef6d-4fed-a865-26a374e722ec/ImagePicker/7A98863B-9F3E-490B-B711-FAA8333FF723.png`

And I get this error:

`RangeError: Array size is not a small enough positive integer.`

Any idea why this is happening ?

Thank you

**Comment by obartra** [comment]
A path is not supported, the loaded image data is required, at least for the recent versions of the library

**Comment by aymeric75** [comment]
Ok, thank you.

I have two questions that could resolve my problem:


1) I have tried to use the "readpixels" function for the Browsers that you give[ here](https://github.com/obartra/ssim/wiki/Node-and-Browsers), but since I am using **React Native** I cannot do:

`const img = new Image()`

or

`const ctx = canvas.getContext('2d')`

So, do you suggest any other solution ?


2) Which former version of your repo should I use to deal directly with the image files ?


Best regards

Aymeric

**Comment by obartra** [comment]
If I recall correctly V1 did V2 maybe as well but it implemented the version that's now in the wiki so that won't work for you.

You could still adapt it to your needs though. The input data format must be a plain object with data, width and height fields. See https://github.com/obartra/ssim/blob/master/src/types.ts#L18

**Comment by aymeric75** [comment]
Ok, thanks, the part where I am stuck is to generate ImageData from an image file in React Native, if you know any solution for this it would be great.
