### ISSUE TITLE
Add WebP Image Support

### ISSUE THREAD

**Issue by domfee** [obartra/ssim#91]
Would you consider adding WebP Image support?

**Comment by obartra** [comment]
Right now it's using `node-canvas` on Node and `<canvas>` on the browser to read the images but if there's an isomorphic WebP library we can use I wouldn't mind. I see [libwebpjs](https://libwebpjs.appspot.com/) may be a good fit

**Comment by obartra** [comment]
Thinking about it a bit more, if you can read the webp image from node you can also feed an image buffer directly to ssimjs

**Comment by obartra** [comment]
Closing for now since an image buffer can be provided
